services:
  postgres:
    container_name: ticket-booking-db
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ticket-booking-network

  app:
    container_name: ticket-booking
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - ticket-booking-network
    restart: always

networks:
  ticket-booking-network:

volumes:
  db-data: